DROP TABLE comments;
DROP TABLE bookings;
DROP TABLE items;
DROP TABLE requests;
DROP TABLE users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(255) NOT NULL,
    requestor_id BIGINT       NOT NULL,
    created      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    is_available BOOLEAN      NOT NULL,
    owner_id     BIGINT       NOT NULL,
    request_id   BIGINT       NULL,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_request_id FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date TIMESTAMP NOT NULL,
    end_date   TIMESTAMP NOT NULL,
    item_id    BIGINT    NOT NULL,
    booker_id  BIGINT    NOT NULL,
    status     INTEGER,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_booker_id FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comment_text VARCHAR(500) NOT NULL,
    item_id      BIGINT       NOT NULL,
    author_id    BIGINT       NOT NULL,
    created      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_author PRIMARY KEY (id),
    CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

INSERT INTO users(NAME, EMAIL)
VALUES ('User1', 'User1@email.com'),
       ('User2', 'User2@email.com'),
       ('User3', 'User3@email.com'),
       ('User4', 'User4@email.com');

INSERT INTO requests(description, requestor_id, created)
VALUES ('Request1 description', 1, '2022-01-01T10:10:10'),
       ('Request2 description', 1, '2022-02-01T10:10:10'),
       ('Request3 description', 1, '2022-03-01T10:10:10'),
       ('Request4 description', 2, '2022-04-01T10:10:10'),
       ('Request5 description', 2, '2022-05-01T10:10:10');

INSERT INTO items(NAME, DESCRIPTION, IS_AVAILABLE, OWNER_ID)
VALUES ('Item1', 'Description1', true, 1),
       ('Item11', 'Description11 for search', false, 1),
       ('Item2', 'Description2', true, 2),
       ('Item22', 'Description22 for SEARCH', true, 2),
       ('Item3', 'Description3', true, 3),
       ('Item33', 'Description33 for SeaRcH', true, 3);

INSERT INTO items(NAME, DESCRIPTION, IS_AVAILABLE, OWNER_ID, REQUEST_ID)
VALUES ('Item4 forsearch', 'Description4', true, 4, 1),
       ('Item44', 'Description44', true, 4, 1);

INSERT INTO bookings(start_date, end_date, item_id, booker_id, status)
VALUES ('2021-01-09T10:10:10', '2021-06-01T10:10:10', 3, 1, 0),
       ('2021-07-01T10:10:10', '2021-12-01T10:10:10', 1, 2, 0),
       ('2022-01-01T10:10:10', '2022-12-30T10:10:10', 3, 1, 0),
       ('2022-01-01T10:10:10', '2022-12-30T10:10:10', 1, 2, 0),
       ('2023-01-01T10:10:10', '2023-06-01T10:10:10', 3, 1, 2),
       ('2023-07-01T10:10:10', '2023-12-01T10:10:10', 1, 2, 2),
       ('2021-01-09T10:10:10', '2021-06-01T10:10:10', 3, 1, 2),
       ('2021-01-01T10:10:10', '2021-12-01T10:10:10', 2, 4, 1);

INSERT INTO comments(comment_text, item_id, author_id, created)
VALUES ('Comment text1', 1, 2, '2022-01-01T10:10:10'),
       ('Comment text2', 1, 2, '2022-02-01T10:10:10'),
       ('Comment text3', 3, 3, '2022-01-01T10:10:10'),
       ('Comment text4', 3, 3, '2022-02-01T10:10:10');